package com.example.chinesonline.core.domain.model

enum class Country(val id: Int, val nativeName: String, val flagEmoji: String) {
    PAIS_NAO_INFORMADO(0, "País não informado", "🏳️"),
    AFEGANISTAO(1, "افغانستان", "🇦🇫"),
    AFRICA_DO_SUL(2, "South Africa", "🇿🇦"),
    ALBANIA(3, "Shqipëria", "🇦🇱"),
    ALEMANHA(4, "Deutschland", "🇩🇪"),
    ANDORRA(5, "Andorra", "🇦🇩"),
    ANGOLA(6, "Angola", "🇦🇴"),
    ANTIGUA_E_BARBUDA(7, "Antigua and Barbuda", "🇦🇬"),
    ARABIA_SAUDITA(8, "العربية السعودية", "🇸🇦"),
    ARGELIA(9, "الجزائر", "🇩🇿"),
    ARGENTINA(10, "Argentina", "🇦🇷"),
    ARMENIA(11, "Հայաստան", "🇦🇲"),
    AUSTRALIA(12, "Australia", "🇦🇺"),
    AUSTRIA(13, "Österreich", "🇦🇹"),
    AZERBAIJAO(14, "Azərbaycan", "🇦🇿"),
    BAHAMAS(15, "Bahamas", "🇧🇸"),
    BANGLADESH(16, "বাংলাদেশ", "🇧🇩"),
    BARBADOS(17, "Barbados", "🇧🇧"),
    BAREIN(18, "البحرين", "🇧🇭"),
    BELARUS(19, "Беларусь", "🇧🇾"),
    BELGICA(20, "België", "🇧🇪"),
    BELIZE(21, "Belize", "🇧🇿"),
    BENIN(22, "Bénin", "🇧🇯"),
    BOLIVIA(23, "Bolivia", "🇧🇴"),
    BOSNIA_E_HERZEGOVINA(24, "Bosna i Hercegovina", "🇧🇦"),
    BOTSUANA(25, "Botswana", "🇧🇼"),
    BRASIL(26, "Brasil", "🇧🇷"),
    BRUNEI(27, "Brunei", "🇧🇳"),
    BULGARIA(28, "България", "🇧🇬"),
    BURKINA_FASO(29, "Burkina Faso", "🇧🇫"),
    BURUNDI(30, "Uburundi", "🇧🇮"),
    BUTAO(31, "འབྲུག་ཡུལ་", "🇧🇹"),
    CABO_VERDE(32, "Cabo Verde", "🇨🇻"),
    CAMAROES(33, "Cameroun", "🇨🇲"),
    CAMBOJA(34, "Kâmpŭchéa", "🇰🇭"),
    CANADA(35, "Canada", "🇨🇦"),
    CATAR(36, "قطر", "🇶🇦"),
    CAZAQUISTAO(37, "Қазақстан", "🇰🇿"),
    CHADE(38, "Tchad", "🇹🇩"),
    CHILE(39, "Chile", "🇨🇱"),
    CHINA(40, "中国", "🇨🇳"),
    CHIPRE(41, "Κύπρος", "🇨🇾"),
    COLOMBIA(42, "Colombia", "🇨🇴"),
    COMORES(43, "Komori", "🇰🇲"),
    CONGO(44, "Congo", "🇨🇬"),
    COREIA_DO_NORTE(45, "조선", "🇰🇵"),
    COREIA_DO_SUL(46, "한국", "🇰🇷"),
    COSTA_DO_MARFIM(47, "Côte d'Ivoire", "🇨🇮"),
    COSTA_RICA(48, "Costa Rica", "🇨🇷"),
    CROACIA(49, "Hrvatska", "🇭🇷"),
    CUBA(50, "Cuba", "🇨🇺"),
    DINAMARCA(51, "Danmark", "🇩🇰"),
    DJIBUTI(52, "Djibouti", "🇩🇯"),
    DOMINICA(53, "Dominica", "🇩🇲"),
    EGITO(54, "مصر", "🇪🇬"),
    EL_SALVADOR(55, "El Salvador", "🇸🇻"),
    EMIRADOS_ARABES_UNIDOS(56, "الإمارات العربية المتحدة", "🇦🇪"),
    EQUADOR(57, "Ecuador", "🇪🇨"),
    ERITREIA(58, "Ertra", "🇪🇷"),
    ESLOVAQUIA(59, "Slovensko", "🇸🇰"),
    ESLOVENIA(60, "Slovenija", "🇸🇮"),
    ESPANHA(61, "España", "🇪🇸"),
    ESTADOS_UNIDOS(62, "United States", "🇺🇸"),
    ESTONIA(63, "Eesti", "🇪🇪"),
    ESWATINI(64, "eSwatini", "🇸🇿"),
    ETIOPIA(65, "ኢትዮጵያ", "🇪🇹"),
    FIJI(66, "Fiji", "🇫🇯"),
    FILIPINAS(67, "Pilipinas", "🇵🇭"),
    FINLANDIA(68, "Suomi", "🇫🇮"),
    FRANCA(69, "France", "🇫🇷"),
    GABAO(70, "Gabon", "🇬🇦"),
    GAMBIA(71, "Gambia", "🇬🇲"),
    GANA(72, "Ghana", "🇬🇭"),
    GEORGIA(73, "საქართველო", "🇬🇪"),
    GRANADA(74, "Grenada", "🇬🇩"),
    GRECIA(75, "Ελλάδα", "🇬🇷"),
    GUATEMALA(76, "Guatemala", "🇬🇹"),
    GUIANA(77, "Guyana", "🇬🇾"),
    GUINE(78, "Guinée", "🇬🇳"),
    GUINE_BISSAU(79, "Guiné-Bissau", "🇬🇼"),
    GUINE_EQUATORIAL(80, "Guinea Ecuatorial", "🇬🇶"),
    HAITI(81, "Haïti", "🇭🇹"),
    HONDURAS(82, "Honduras", "🇭🇳"),
    HUNGRIA(83, "Magyarország", "🇭🇺"),
    IEMEN(84, "اليمن", "🇾🇪"),
    ILHAS_MARSHALL(85, "Marshall Islands", "🇲🇭"),
    ILHAS_SALOMAO(86, "Solomon Islands", "🇸🇧"),
    INDIA(87, "भारत", "🇮🇳"),
    INDONESIA(88, "Indonesia", "🇮🇩"),
    IRA(89, "ایران", "🇮🇷"),
    IRAQUE(90, "العراق", "🇮🇶"),
    IRLANDA(91, "Éire", "🇮🇪"),
    ISLANDIA(92, "Ísland", "🇮🇸"),
    ISRAEL(93, "ישראל", "🇮🇱"),
    ITALIA(94, "Italia", "🇮🇹"),
    JAMAICA(95, "Jamaica", "🇯🇲"),
    JAPAO(96, "日本", "🇯🇵"),
    JORDANIA(97, "الأردن", "🇯🇴"),
    KIRIBATI(98, "Kiribati", "🇰🇮"),
    KUWAIT(99, "الكويت", "🇰🇼"),
    LAOS(100, "ປະເທດລາວ", "🇱🇦"),
    LESOTO(101, "Lesotho", "🇱🇸"),
    LETONIA(102, "Latvija", "🇱🇻"),
    LIBANO(103, "لبنان", "🇱🇧"),
    LIBERIA(104, "Liberia", "🇱🇷"),
    LIBIA(105, "ليبيا", "🇱🇾"),
    LIECHTENSTEIN(106, "Liechtenstein", "🇱🇮"),
    LITUANIA(107, "Lietuva", "🇱🇹"),
    LUXEMBURGO(108, "Lëtzebuerg", "🇱🇺"),
    MACEDONIA_DO_NORTE(109, "Северна Македонија", "🇲🇰"),
    MADAGASCAR(110, "Madagasikara", "🇲🇬"),
    MALASIA(111, "Malaysia", "🇲🇾"),
    MALAUI(112, "Malawi", "🇲🇼"),
    MALDIVAS(113, "Maldives", "🇲🇻"),
    MALI(114, "Mali", "🇲🇱"),
    MALTA(115, "Malta", "🇲🇹"),
    MARROCOS(116, "المغرب", "🇲🇦"),
    MAURICIO(117, "Maurice", "🇲🇺"),
    MAURITANIA(118, "موريتانيا", "🇲🇷"),
    MEXICO(119, "México", "🇲🇽"),
    MICRONESIA(120, "Micronesia", "🇫🇲"),
    MOCAMBIQUE(121, "Moçambique", "🇲🇿"),
    MOLDAVIA(122, "Moldova", "🇲🇩"),
    MONACO(123, "Monaco", "🇲🇨"),
    MONGOLIA(124, "Монгол улс", "🇲🇳"),
    MONTENEGRO(125, "Crna Gora", "🇲🇪"),
    MIANMAR(126, "မြန်မာ", "🇲🇲"),
    NAMIBIA(127, "Namibia", "🇳🇦"),
    NAURU(128, "Nauru", "🇳🇷"),
    NEPAL(129, "नेपाल", "🇳🇵"),
    NICARAGUA(130, "Nicaragua", "🇳🇮"),
    NIGER(131, "Niger", "🇳🇪"),
    NIGERIA(132, "Nigeria", "🇳🇬"),
    NORUEGA(133, "Norge", "🇳🇴"),
    NOVA_ZELANDIA(134, "New Zealand", "🇳🇿"),
    OMA(135, "عمان", "🇴🇲"),
    PAISES_BAIXOS(136, "Nederland", "🇳🇱"),
    PALAU(137, "Palau", "🇵🇼"),
    PANAMA(138, "Panamá", "🇵🇦"),
    PAPUA_NOVA_GUINE(139, "Papua New Guinea", "🇵🇬"),
    PAQUISTAO(140, "پاکستان", "🇵🇰"),
    PARAGUAI(141, "Paraguay", "🇵🇾"),
    PERU(142, "Perú", "🇵🇪"),
    POLONIA(143, "Polska", "🇵🇱"),
    PORTUGAL(144, "Portugal", "🇵🇹"),
    QUENIA(145, "Kenya", "🇰🇪"),
    QUIRGUISTAO(146, "Кыргызстан", "🇰🇬"),
    REINO_UNIDO(147, "United Kingdom", "🇬🇧"),
    REPUBLICA_CENTRO_AFRICANA(148, "Ködörösêse tî Bêafrîka", "🇨🇫"),
    REPUBLICA_CHECA(149, "Česko", "🇨🇿"),
    REPUBLICA_DEMOCRATICA_DO_CONGO(150, "République démocratique du Congo", "🇨🇩"),
    REPUBLICA_DOMINICANA(151, "República Dominicana", "🇩🇴"),
    ROMENIA(152, "România", "🇷🇴"),
    RUANDA(153, "Rwanda", "🇷🇼"),
    RUSSIA(154, "Россия", "🇷🇺"),
    SAMOA(155, "Samoa", "🇼🇸"),
    SAN_MARINO(156, "San Marino", "🇸🇲"),
    SANTA_LUCIA(157, "Saint Lucia", "🇱🇨"),
    SAO_CRISTOVAO_E_NEVIS(158, "Saint Kitts and Nevis", "🇰🇳"),
    SAO_TOME_E_PRINCIPE(159, "São Tomé e Príncipe", "🇸🇹"),
    SAO_VICENTE_E_GRANADINAS(160, "Saint Vincent and the Grenadines", "🇻🇨"),
    SEICHELES(161, "Seychelles", "🇸🇨"),
    SENEGAL(162, "Sénégal", "🇸🇳"),
    SERRA_LEOA(163, "Sierra Leone", "🇸🇱"),
    SERVIA(164, "Србија", "🇷🇸"),
    SINGAPURA(165, "Singapore", "🇸🇬"),
    SIRIA(166, "سوريا", "🇸🇾"),
    SOMALIA(167, "Soomaaliya", "🇸🇴"),
    SRI_LANKA(168, "Sri Lanka", "🇱🇰"),
    SUDAO(169, "السودان", "🇸🇩"),
    SUDAO_DO_SUL(170, "South Sudan", "🇸🇸"),
    SUECIA(171, "Sverige", "🇸🇪"),
    SUICA(172, "Schweiz", "🇨🇭"),
    SURINAME(173, "Suriname", "🇸🇷"),
    TAILANDIA(174, "ประเทศไทย", "🇹🇭"),
    TAJIQUISTAO(175, "Тоҷикистон", "🇹🇯"),
    TANZANIA(176, "Tanzania", "🇹🇿"),
    TIMOR_LESTE(177, "Timor-Leste", "🇹🇱"),
    TOGO(178, "Togo", "🇹🇬"),
    TONGA(179, "Tonga", "🇹🇴"),
    TRINDADE_E_TOBAGO(180, "Trinidad and Tobago", "🇹🇹"),
    TUNISIA(181, "تونس", "🇹🇳"),
    TURCOMENISTAO(182, "Türkmenistan", "🇹🇲"),
    TURQUIA(183, "Türkiye", "🇹🇷"),
    TUVALU(184, "Tuvalu", "🇹🇻"),
    UCRANIA(185, "Україна", "🇺🇦"),
    UGANDA(186, "Uganda", "🇺🇬"),
    URUGUAI(187, "Uruguay", "🇺🇾"),
    UZBEQUISTAO(188, "Oʻzbekiston", "🇺🇿"),
    VANUATU(189, "Vanuatu", "🇻🇺"),
    VATICANO(190, "Vaticano", "🇻🇦"),
    VENEZUELA(191, "Venezuela", "🇻🇪"),
    VIETNA(192, "Việt Nam", "🇻🇳"),
    ZAMBIA(193, "Zambia", "🇿🇲"),
    ZIMBABUE(194, "Zimbabwe", "🇿🇼")
}
